config/routes.rb
Rails.application.routes.draw do

 root :to => "public/homes#top"
 get "homes/about"=>"public/homes#about", as:"about"

 namespace :admin do
   root to: "homes#top"
   resources :homes
   resources :items

   resources:genres, only: [:index,:create,:edit, :update]
   resources:customers, only: [:index, :show, :edit, :update]

   resources:orders
   resources:order_details
 end


  namespace :public do
    resources :homes
    resources:items ,only: [:index, :show]
    delete 'cart_items/all_destroy' => 'cart_items#all_destroy', as: "all_destroy_cart_itmes"
    resources:cart_items ,only: [:index, :update, :create, :destroy]
    get 'customers/my_page' => 'customers#show', as: "customer"
    get 'customers/information/edit' => 'customers#edit', as: "customers_edit"
    patch 'customers/information' => 'customers#update'
    get 'customers/unsubscribe' => 'customers#unsubscribe'
    patch 'customers/withdraw' => 'customers#withdraw'
    post 'orders/confirm', to: 'orders#confirm'
    get "orders/complete" => "orders#complete", as: "complete"
    resources:orders
    resources:addresses, only: [:index, :create, :edit, :update, :destroy]
  end

  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }
  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }
  
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :addresses
  has_many :cart_items, dependent: :destroy
  has_many :orders

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :first_name,presence:true
  validates :last_name,presence:true
  validates :first_name_kana,presence:true
  validates :last_name_kana,presence:true
  validates :postcode,presence:true,length: { is: 7 }
  # ７桁のバリデーションがかかって保存されない

  def full_address
    '〒'+postcode+' '+address
  end

  def self.search(search,word)
    if search == "forward"
      @customers = Customer.where("first_name LIKE?","#{word}%")
    elsif search =="partial"
      @customers = Customer.where("first_name LIKE?","%#{word}%")
    else
      @customers = Customer.all
    end
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!
  
  def index
     @customers = Customer.all
    #@customers = Customer.all.page(params[:page])
    # @customers = Customer.page(params[:page])
  end
  
  def show
    # # @customers = Customer.all
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customer_path(@customer.id)
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :email, :is_deleted, :telephone_number, :customer_status)
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
    <div class="row">
      <div class="col m-10">
        <p id="notice"></p><h2>会員情報編集</h2>
        <%= form_for(@customer, url: admin_customer_path(@customer)) do |f| %>
          <table class="row table">

            <tr>
              <th><%= f.label :氏名 %></th>
              <th>(姓)</th>
              <th><%= f.text_field :first_name, class:"form-control" %></th>
              <th>(名)</th>
              <th><%= f.text_field :last_name, class:"form-control" %></th>
              </td>
            </tr>

            <tr>
              <th><%= f.label :フリガナ %></th>
              <th>(セイ)</th>
              <th><%= f.text_field :first_name_kana, class:"form-control" %></th>
              <th>(メイ)</th>
              <th><%= f.text_field :last_name_kana, class:"form-control" %></th>
            </tr>

            <tr>
              <th><%= f.label :郵便番号 %></th>
              <th></th>
              <td><%= f.text_field :postcode, class:"form-control" %></td>
              <th></th><th></th>
            </tr>

            <tr>
              <th><%= f.label :住所 %></th>
              <th></th>
              <td><%= f.text_field :address, class:"form-control" %></td>
              <th></th><th></th>
            </tr>

            <tr>
              <th><%= f.label :電話番号 %></th>
              <th></th>
              <td><%= f.text_field :telephone_number, class:"form-control" %></td>
              <th></th><th></th>
            </tr>

            <tr>
              <th><%= f.label :メールアドレス %></th>
              <th></th>
              <td><%= f.text_field :email , class:"form-control"%></td>
              <th></th><th></th>
            </tr>

            <tr>
              <th><%= f.label :会員ステータス %></th>
              <th></th>
              <td><%= f.radio_button :is_deleted, false %>
                  <%= f.label :is_deleted, '有効会員', value: false %>
              </td>
              <th></th>
               <td><%= f.radio_button :is_deleted, true %>
                  <%= f.label :is_deleted, '退会済み', value: true %>
              </td>
            </tr>
          </table>
        <div class="row text-right">
          <%= f.submit "変更を保存する" ,class: "btn btn-outline-success " %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-10 col-xs-offset-1">
      <h2>会員一覧</h2>

      <table class="table">
        <thead>
          <tr>
            <th>会員ID</th>
            <th>氏名</th>
            <th>メールアドレス</th>
            <th></th>
            <th>ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @customers.each do |customer| %>
          <!--each文→複数のものを取り出す。doで右側に一番を格納する。||=customer.find1番-->
            <tr>
              <td><%= customer.id %></td>
              <!--画像と文字link to do -->
              <td><%= link_to admin_customer_path(customer) do %> <%= customer.first_name %> <%= customer.last_name %> <% end %></td>
              <!--ブロック変数は@がいらない-->
              <td><%= customer.email %></td>
              <td>
                <% if customer.is_deleted? == true %>
                  <td class="text-danger text-center">退会</td>
  		          <% else %>
  		            <td class="text-success text-center">有効</td>
  		          <% end %>
              </td>
            </tr>
          <% end %>
            <!--each~endまで来たら繰り返し。２番以降からデータがなくなるまで繰り返す。-->
        </tbody>
      </table>
       <!--paginate @customers %>-->
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row">
    <div class="col m-10">
      <h2 class="text-black"><%= @customer.first_name %><%= @customer.last_name %>さんの会員詳細</h2>
      <table class="table table-borderless" style="opacity: 0.8;">
        <tbody>
          <tr>
            <th>会員ID</th>
            <td><%= @customer.id %></td>
          </tr>
          <tr>
            <th>氏名</th>
            <td><%= @customer.first_name %>&nbsp;&nbsp;<%= @customer.last_name %></td>
          </tr>
          <tr>
            <th>フリガナ</th>
            <td><%= @customer.first_name_kana %>&nbsp;&nbsp;<%= @customer.last_name_kana %></td>
          </tr>
          <tr>
            <th>郵便番号</th>
            <td>〒<%= @customer.postcode %></td>
          </tr>
          <tr>
            <th>住所</th>
            <td><%= @customer.address %></td>
          </tr>
          <tr>
            <th>電話番号</th>
            <td><%= @customer.telephone_number %></td>
          </tr>
          <tr>
            <th>メールアドレス</th>
            <td><%= @customer.email %></td>
          </tr>
          <tr>
            <th>会員ステータス</th>
            <% if @customer.is_deleted? == true %>
    	        <td class="text-danger">退会</td>
				    <% else %>
				      <td class="text-success">有効</td>
				    <% end %>
          </tr>
        </tbody>
      </table>
      <div class="text-center mb-3">
        <div class="d-inline-block mr-5">
          <%= link_to '編集する', edit_admin_customer_path, class:"btn btn-outline-success" %>
        </div>
        <div class="d-inline-block ml-5">
          <%= link_to '会員一覧に戻る',admin_customers_path, class:"btn btn-outline-primary" %>
        </div>
      </div>
    </div>
  </div>
</div>