config/routes.rb
Rails.application.routes.draw do

 root :to => "public/homes#top"
 get "homes/about"=>"public/homes#about", as:"about"

 namespace :admin do
   root to: "homes#top"
   resources :homes
   resources :items

   resources:genres, only: [:index,:create,:edit, :update]
   resources:customers, only: [:index, :show, :edit, :update]

   resources:orders
   resources:order_details
 end


  namespace :public do
    resources :homes
    resources:items ,only: [:index, :show]
    delete 'cart_items/all_destroy' => 'cart_items#all_destroy', as: "all_destroy_cart_itmes"
    resources:cart_items ,only: [:index, :update, :create, :destroy]
    get 'customers/my_page' => 'customers#show', as: "customer"
    get 'customers/information/edit' => 'customers#edit', as: "customers_edit"
    patch 'customers/information' => 'customers#update'
    get 'customers/unsubscribe' => 'customers#unsubscribe'
    patch 'customers/withdraw' => 'customers#withdraw'
    post 'orders/confirm', to: 'orders#confirm'
    get "orders/complete" => "orders#complete", as: "complete"
    resources:orders
    resources:addresses, only: [:index, :create, :edit, :update, :destroy]
  end

  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }
  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }
  
end

app/models/order.rb
class Order < ApplicationRecord

    has_many :order_details
    enum payment_method: { credit_card: 0, transfer: 1 }
    enum status: { payment_waiting: 0, payment_confirmation: 1, in_production: 2, preparing_delivery: 3, delivered: 4 }
    belongs_to :customer
    has_many :items, through: :order_details

  attribute :shipping_cost, default: 800

  def subtotal
    item.with_tax_price * amount
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
 before_action :authenticate_admin!


  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    @order_details = @order.order_details
 # 注文ステータスが"入金確認"になったら製作ステータスを"製作待ち"
    if @order.status == "payment_confirmation"
      # @order_details.each do |order_detail|
        # order_detail.making_status = "製作待ち"
        @order.order_details.update(making_status: "awaiting")
      # end
    end
    redirect_to admin_order_path(@order)
  end

  private
  def order_params
   params.require(:order).permit(:customer_id, :name, :postal_code, :address, :payment_method, :status, :price, :shipping_cost )

  end

end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="row">
    <h1>　注文履歴詳細</h1>
    <table class="table table-bordered">
      <tr>
  			<th class='col-sm-3'>購入者</th>
  			<td><%= link_to  admin_customer_path(@order) do %>
  					<%= @order.customer.first_name %>　<%= @order.customer.last_name %>
  					<% end %>
  			</td>
  		</tr>
  		<tr>
  			<th class='col-sm-3'>注文日</th>
  			<td>
  		    <%= @order.created_at.strftime("%Y/%m/%d %H:%M:%S") %>
  			</td>
  		</tr>
  		<tr>
  			<th class='col-sm-3'>配送先</th>
  			<td><%= @order.address %></td>
  		</tr>
  		<tr>
  			<th class='col-sm-3'>支払方法</th>
  			<td><%= @order.payment_method_i18n %></td>
  		</tr>
  			<tr>
  			<th class='col-sm-3'>注文ステータス</th>
    		<td>
      		<%= form_with model:@order, url: admin_order_path, local: true do |f| %>
                <%= f.select :status,[ ["入金待ち",'payment_waiting'], [ "入金確認",'payment_confirmation'], ["製作中",'in_production'], ["発送準備中",'preparing_delivery'], ["発送済み",'delivered'] ]%>
                <%= f.submit "更新", class: 'btn btn-outline-primary' %>
          <% end %>
    		</td>
			</tr>
    </table>
　</div>
  <div class="row">
　  <div class='col-md-8'>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th>商品名</th>
            <th>単価(税込)</th>
            <th>数量</th>
            <th>小計</th>
            <th>制作ステータス</th>
          </tr>
        </thead>
        <% @order_details.each do |order_detail| %>
        　<tbody>
            <tr>
             <td><%= order_detail.item.name %></td>
             <td><%= (order_detail.price).floor.to_s(:delimited) %></td>
             <td><%= order_detail.amount %></td>
             <td><%= ((order_detail.price * order_detail.amount).floor).to_s(:delimited) %></td>
             <td>
                <%= form_with model: order_detail, url: admin_order_detail_path(order_detail.id), local: true do |f| %>
                  <%= f.select :making_status, [["製作不可",'cannot'], ["製作待ち",'awaiting'], ["製作中",'in_production'], ["製作完了",'complete'] ]%>
                  <%= f.submit "更新", class: 'btn btn-outline-primary' %>
                <% end %>
              </td>
             </tr>
          </tbody>
        <% end %>
      </table>
    </div>
    <div class='col-md-3 text-right'>
      <table class="table table-borderless">
        <tr><th></th><td></td></tr>
        <tr><th></th><td></td></tr>
        <tr>
          <th><strong>商品合計</strong></th>
          <td><%= (@order.total_payment - @order.shipping_cost).to_s(:delimited)%>円</td>
        </tr>
        <tr>
          <th><strong>送料</strong></th>
          <td><%= @order.shipping_cost %>円</td>
        </tr>
        <tr>
          <th><strong>請求金額合計</strong></th>
          <td><%= @order.total_payment.to_s(:delimited) %>円</td>
        </tr>
      </table>
    </div>
  </div>
</div>