config/routes.rb
Rails.application.routes.draw do

 root :to => "public/homes#top"
 get "homes/about"=>"public/homes#about", as:"about"

 namespace :admin do
   root to: "homes#top"
   resources :homes
   resources :items

   resources:genres, only: [:index,:create,:edit, :update]
   resources:customers, only: [:index, :show, :edit, :update]

   resources:orders
   resources:order_details
 end


  namespace :public do
    resources :homes
    resources:items ,only: [:index, :show]
    delete 'cart_items/all_destroy' => 'cart_items#all_destroy', as: "all_destroy_cart_itmes"
    resources:cart_items ,only: [:index, :update, :create, :destroy]
    get 'customers/my_page' => 'customers#show', as: "customer"
    get 'customers/information/edit' => 'customers#edit', as: "customers_edit"
    patch 'customers/information' => 'customers#update'
    get 'customers/unsubscribe' => 'customers#unsubscribe'
    patch 'customers/withdraw' => 'customers#withdraw'
    post 'orders/confirm', to: 'orders#confirm'
    get "orders/complete" => "orders#complete", as: "complete"
    resources:orders
    resources:addresses, only: [:index, :create, :edit, :update, :destroy]
  end

  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }
  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }
  
end

app/models/address.rb
class Address < ApplicationRecord
    belongs_to :customer

  validates :postal_code, presence: true, format: { with: /\A\d{7}\z/ }
  validates :address, presence: true
  validates :name, presence: true

  def finally_address
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

def subtotal
    item.with_tax_price * amount
end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :addresses
  has_many :cart_items, dependent: :destroy
  has_many :orders

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :first_name,presence:true
  validates :last_name,presence:true
  validates :first_name_kana,presence:true
  validates :last_name_kana,presence:true
  validates :postcode,presence:true,length: { is: 7 }
  # ７桁のバリデーションがかかって保存されない

  def full_address
    '〒'+postcode+' '+address
  end

  def self.search(search,word)
    if search == "forward"
      @customers = Customer.where("first_name LIKE?","#{word}%")
    elsif search =="partial"
      @customers = Customer.where("first_name LIKE?","%#{word}%")
    else
      @customers = Customer.all
    end
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
  validates :name, presence: true, length: { minimum: 2, maximum: 20 }
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details
  
  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true
  validates :genre_id, presence: true
  
  def with_tax_price
        (price * 1.1).floor
  end
  
end

app/models/order.rb
class Order < ApplicationRecord

    has_many :order_details
    enum payment_method: { credit_card: 0, transfer: 1 }
    enum status: { payment_waiting: 0, payment_confirmation: 1, in_production: 2, preparing_delivery: 3, delivered: 4 }
    belongs_to :customer
    has_many :items, through: :order_details

  attribute :shipping_cost, default: 800

  def subtotal
    item.with_tax_price * amount
  end

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
   belongs_to :order
    enum making_status: {cannot: 0, awaiting: 1, in_production: 2, complete: 3}
    belongs_to :item

    def self.cart_products_total_price(cart_products)
    array = []
    cart_products.each do |cart_product|
      array << cart_product.product.price * cart_product.amount
    end
    return (array.sum * 1.1).floor
    end

    def subtotal
    item.with_tax_price * amount
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!

  def top
    @orders = Order.all
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item)
    else
      redirect_to new_admin_item_path, notice: "大変申し訳ありませんが記入漏れがあります"
    end
  end


  def index
    @item = Item.new
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update!(item_params)
      redirect_to admin_item_path(@item), notice: "無事に更新されました"
    else
<<<<<<< HEAD
    render "edit"
=======
      render 'edit'
>>>>>>> origin/develop
    end
  end

  private
  def item_params
    params.require(:item).permit(:name, :introduction, :genre_id, :price, :is_active, :image)
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters,if: :devise_controller?
    def after_sign_out_path_for(resource_or_scope)
        return new_admin_session_path if resource_or_scope == :admin
        return root_path if resource_or_scope == :customer
    end

    #サインイン後の遷移先を指定する
    def after_sign_in_path_for(resource)
        case resource
        when Admin
         admin_root_path
        when Customer
         root_path
        end
    end

    protected
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :first_name_kana, :last_name_kana, :postcode, :address, :telephone_number])
    end
    # 許可したいもの全て
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<!--<%#- if devise_mapping.registerable? && controller_name != 'registrations' %>-->
<!--  <%#= link_to "Sign up", new_registration_path(resource_name) %><br />-->
<!--<%# end %>-->

<!--<%#- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>-->
<!--  <%#= link_to "Forgot your password?", new_password_path(resource_name) %><br />-->
<!--<%# end %>-->

<!--<%#- if devise_mapping.confirmable? && controller_name != 'confirmations' %>-->
<!--  <%#= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />-->
<!--<%# end %>-->

<!--<%#- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>-->
<!--  <#= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />-->
<!--<%# end %>-->

<!--<%#- if devise_mapping.omniauthable? %>-->
<!--  <%#- resource_class.omniauth_providers.each do |provider| %>-->
<!--    <%#= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />-->
<!--  <%# end %>-->
<!--<%# end %>-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>



  <header class="shadow-sm mb-5" >
        <nav class="navbar expand-lg navbar-dark" style="background-color: #ffdab9;">

          <div class="container">
            <% if admin_signed_in? %>
              <%= link_to admin_root_path do %>
                <%= image_tag "logo.png", size: "300x76" %>
              <% end %>
              <ul class="nav justify-content-end">
                <li class="nav-item btn"><%= link_to "商品一覧", admin_items_path, class: 'nav-link text-dark' %></li>
                <li class="nav-item btn"><%= link_to "会員一覧", admin_customers_path, class: 'nav-link text-dark' %></li>
                <li class="nav-item btn"><%= link_to "注文履歴一覧", admin_root_path, class: 'nav-link text-dark' %></li>
                <li class="nav-item btn"><%= link_to "ジャンル一覧", admin_genres_path, class: 'nav-link text-dark' %></li>
                <li class="nav-item btn"><%= link_to "ログアウト",  destroy_admin_session_path, method: :delete, class: 'nav-link text-dark' %></li>
              </ul>
            <% elsif customer_signed_in? %>
              <%= link_to root_path do %>
                <%= image_tag "logo.png", size: "300x76" %>
              <% end %>
              <ul class="nav justify-content-end">
                <li class="nav-item btn"><%= link_to "マイページ", public_customer_path(current_customer.id), class: 'nav-link text-dark' %></li>
                <li class="nav-item btn"><%= link_to "商品一覧", public_items_path, class: 'nav-link text-dark' %></li>
                <li class="nav-item btn"><%= link_to "カート", public_cart_items_path(current_customer.id), class: 'nav-link text-dark' %></li>
                <li class="nav-item btn"><%= link_to "ログアウト",  destroy_customer_session_path, method: :delete, class: 'nav-link text-dark' %></li>
              </ul>
            <% else %>
              <%= link_to root_path do %>
                <%= image_tag "logo.png", size: "300x76" %>
              <% end %>
              <ul class="nav justify-content-end">
                <li class="nav-item btn"><%= link_to "About", about_path, class: 'nav-link text-dark' %></li>
                <li class="nav-item btn"><%= link_to "商品一覧", public_items_path, class: 'nav-link text-dark' %></li>
                <li class="nav-item btn"><%= link_to "新規登録", new_customer_registration_path, class: 'nav-link text-dark' %></li>
                <li class="nav-item btn"><%= link_to "ログイン", new_customer_session_path, class: 'nav-link text-dark' %></li>
              </ul>
            <% end %>
          </div>
        </nav>
      </header>
      
        <%= yield %>
        
      <footer class="text-dark pt-5 pb-3">
        <div class='container'>
    	    <div class='row'>
      	    <div class='mx-auto'>
                <a href="#" class="mx-1 text-dark"><i class="fab fa-twitter fa-lg"></i></a>
                <a href="#" class="mx-5 text-dark"><i class="fab fa-instagram fa-lg"></i></a>
                <a href="#" class="mx-1 text-dark"><i class="fab fa-facebook-square"></i></a>
                <a href="#" class="mx-5 text-dark"><i class="far fa-envelope fa-lg"></i></a>
                <p class="text-center">からあげ</p>
              </div>
           </div>
         </div>
      </footer>
      
  </body>
</html>